language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
script:
  - yarn run build
after_success:
  - yarn run build
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
